name: my build
on:
  push:
    branches: main

jobs:
  build-with-maven:
    name: build-job
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distruction: adopt

      - name: build with maven
        run: mvn -B package --file pom.xml



