name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Build and Run Tests
        run: mvn test --batch-mode --fail-at-end
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1

  push_to_registry:
    name: Push Docker image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          rev=$(git rev-parse --short HEAD)
          docker build . -t devops-app1
          docker tag devops-app1 244530008913.dkr.ecr.eu-west-1.amazonaws.com/hali015-private:$rev
          docker tag devops-app1 244530008913.dkr.ecr.eu-west-1.amazonaws.com/hali015-private:latest
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/hali015-private:$rev
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/hali015-private:latest


